### ISSUE TITLE
my theme folder is been removed

### ISSUE THREAD

**Issue by jampow** [shovelandsandbox/glacier-theme#32]
when I start my sublime the theme is loaded but in the same time the folder is removed and the theme starts to crash. Is this a sublime bug or a theme bug?

tks

**Comment by jampow** [comment]
I found this log message in console

```
...
Package Control: Removed directory for orphaned package Theme - Glacier
Package Control: Skipping automatic upgrade, last run at 2015-02-19 17:56:15, next run at 2015-02-19 18:56:15 or after
found 1 files for base name Glacier.sublime-theme
unloading plugin Theme - Glacier.events
found 1 files for base name Glacier.sublime-theme
reloading Packages/Theme - Glacier/Glacier/Widget - Glacier.sublime-settings
Errors parsing theme:
top level value must be an array
theme loaded
Errors parsing theme:
top level value must be an array
theme loaded
Unable to decode Packages/Theme - Glacier/Glacier/buffer.png
Unable to decode Packages/Theme - Glacier/Glacier/casesens.png
Unable to decode Packages/Theme - Glacier/Glacier/circle@2x.png
...
```

it seems package control doesn't like orphan packages... xp

**Comment by joeyfigaro** [comment]
Just the ammunition needed to get this resolved. Thanks @jampow - I'll look into it!

**Comment by joeyfigaro** [comment]
@jampow does this issue occur when you attempt to install [Soda Theme](https://github.com/buymeasoda/soda-theme)?

Reaching out to package control to learn more about orphaned packages too, if you've run across any documentation.

**Comment by joeyfigaro** [comment]
![](https://s3.amazonaws.com/f.cl.ly/items/0i0Z1a1d233b35092j3Q/Image%202015-02-23%20at%2010.29.28%20AM.png)
@jampow Received a response from @wbond and have updated the repo to remove the problematic file.
