### ISSUE TITLE
Most text is purple-red now with Sublime Text 3103

### ISSUE THREAD

**Issue by Uptown76** [shovelandsandbox/glacier-theme#37]
I just upgraded Sublime text to build 3013. Most variables are the purple-red colour now. I have only looked at Javascript files. Javascript objects are also yellow now.

**Comment by joehenry087** [comment]
I also experienced the same thing.

**Comment by astrism** [comment]
Same here, I'm really missing the old coloring.

**Comment by joeyfigaro** [comment]
@Uptown76 @joehenry087 @astrism Can you guys get me some screenshots?

**Comment by joehenry087** [comment]
@joeyfigaro sorry, I don't remember how i fixed this but it was a long time ago. Totally forgot about it.

**Comment by joeyfigaro** [comment]
Closing this for now since #44 is coming down the pike—can open up new tickets/revive this if required.
